version: 2

workflows:
  version: 2
  build:
    jobs:
      - python-3.7
      - python-3.8
      - python-3.9
      - python-3.10
      - python-3.11
      - deploy:
          context: pypi
          requires:
            - python-3.7
          filters:
            branches:
              only: release

jobs:
  python-3.7: &build-template
    working_directory: ~/app
    docker:
      - image: cimg/python:3.7
        environment:
          TOX_ENV: py37

    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
            - deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "setup.py" }}-
            - deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - deps-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install -e .[examples]
            tox --notest  # Install all tox dependencies

      - save_cache:
          paths:
            - venv
            - .tox
          key: deps-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

      - run:
          name: run linters
          command: |
            . venv/bin/activate
            tox -e mypy,linter

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e $TOX_ENV

  python-3.8:
    <<: *build-template
    docker:
      - image: cimg/python:3.8
        environment:
          TOX_ENV: py38

  python-3.9:
    <<: *build-template
    docker:
      - image: cimg/python:3.9
        environment:
          TOX_ENV: py39

  python-3.10:
    <<: *build-template
    docker:
      - image: cimg/python:3.10
        environment:
          TOX_ENV: py310

  python-3.11:
    <<: *build-template
    docker:
      - image: cimg/python:3.11
        environment:
          TOX_ENV: py311

  deploy:
    docker:
      - image: cimg/python:3.7

    working_directory: ~/uhlive

    steps:
      - checkout

      - run:
          name: init .pypirc and build env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install wheel twine build
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python -m build

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
