version: 2

workflows:
  version: 2
  build:
    jobs:
      - python-3.7
      - python-3.8
      - python-3.9
      - deploy:
          context: pypi
          requires:
            - python-3.7
          filters:
            branches:
              only: release

jobs:
  python-3.7: &build-template
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7
        environment:
          TOX_ENV: py37

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install -e .[examples]
      - save_cache:
          paths: venv
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - restore_cache:
          key: tox-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e $TOX_ENV

      - run:
          name: run linters
          command: |
            . venv/bin/activate
            tox -e mypy,flake8

      - save_cache:
          paths: .tox
          key: tox-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

  python-3.8:
    <<: *build-template
    docker:
      - image: circleci/python:3.8
        environment:
          TOX_ENV: py38

  python-3.9:
    <<: *build-template
    docker:
      - image: circleci/python:3.9
        environment:
          TOX_ENV: py39

  deploy:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/uhlive

    steps:
      - checkout

      - run:
          name: init .pypirc and build env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip
            pip install wheel twine
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPI_TOKEN" >> ~/.pypirc

      - run:
          name: create packages
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel

      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*
