version: 2

workflows:
  version: 2
  build:
    jobs:
      - python-3.7
      - python-3.8
      - python-3.9
  package:
    jobs:
      - python-3.7:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - package:
          requires:
            - python-3.7
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

jobs:
  python-3.7: &build-template
    working_directory: ~/app
    docker:
      - image: circleci/python:3.7
        environment:
          TOX_ENV: py37

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - run:
          name: install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            pip install -e .[examples]
      - save_cache:
          paths: venv
          key: deps-{{ .Branch }}-{{ checksum "setup.py" }}

      - restore_cache:
          key: tox-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox -e $TOX_ENV

      - run:
          name: run linters
          command: |
            . venv/bin/activate
            tox -e mypy,flake8

      - save_cache:
          paths: .tox
          key: tox-{{ .Branch }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

  python-3.8:
    <<: *build-template
    docker:
      - image: circleci/python:3.8
        environment:
          TOX_ENV: py38

  python-3.9:
    <<: *build-template
    docker:
      - image: circleci/python:3.9
        environment:
          TOX_ENV: py39

  package:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: install wheel
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install wheel

      - run:
          name: create wheel
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel

      - store_artifacts:
          path: dist
