---
version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - tests:
          matrix:
            parameters:
              version:
                - "3.11"
                - "3.12"
                - "3.13"
      - deploy:
          context: pypi
          requires:
            - tests
          filters:
            branches:
              only: release

jobs:
  tests:
    parameters:
      version:
        description: "version tag"
        default: "3.12"
        type: string
    docker:
      - image: cimg/python:<<parameters.version>>

    working_directory: ~/app

    steps:
      - checkout

      - restore_cache:
          keys:
            - <<parameters.version>>-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-{{ checksum "uv.lock" }}
            - <<parameters.version>>-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-
            - <<parameters.version>>-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-
            - <<parameters.version>>-{{ .Environment.CACHE_VERSION }}-

      - run:
          name: install requirements
          command: |
            uv sync --all-extras

      - save_cache:
          paths:
            - .venv
          key: <<parameters.version>>-{{ .Environment.CACHE_VERSION }}-{{ .Branch }}-{{ checksum "pyproject.toml" }}-{{ checksum "uv.lock" }}

      - run:
          name: run linters
          command: |
            uv run ruff check src examples tests
            uv run mypy src examples tests

      - run:
          name: run tests
          command: |
            uv run python -m unittest discover

  deploy:
    resource_class: small
    docker:
      - image: cimg/python:3.12

    working_directory: ~/uhlive

    steps:
      - checkout

      - run:
          name: create packages
          command: |
            uv build

      - run:
          name: upload to pypi
          command: |
            uv publish --username __token__ --password $PYPI_TOKEN
